# Generated by Django 5.2.8 on 2025-11-13 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_whatsapp', models.CharField(default='+257 69 08 02 78', max_length=20)),
                ('email', models.EmailField(default='karinzi.bi.sab@gmail.com', max_length=254)),
                ('adresse', models.CharField(default='Bujumbura - Burundi, bldg Saint Pierre Avenue de l’OUA', max_length=255)),
            ],
            options={
                'verbose_name': 'Information de contact',
                'verbose_name_plural': 'Informations de contact',
            },
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Marque',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles', to='voitures.marque')),
            ],
            options={
                'verbose_name': 'Modèle',
                'verbose_name_plural': 'Modèles',
                'ordering': ['nom'],
                'unique_together': {('marque', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chassis', models.CharField(max_length=100, unique=True)),
                ('numero_moteur', models.CharField(max_length=100)),
                ('annee', models.PositiveIntegerField()),
                ('transmission', models.CharField(choices=[('Manuelle', 'Manuelle'), ('Automatique', 'Automatique'), ('Autre', 'Autre')], max_length=20)),
                ('kilometrage', models.FloatField(help_text='Distance parcourue en kilomètres')),
                ('couleur', models.CharField(max_length=50)),
                ('cylindree_cc', models.PositiveIntegerField(verbose_name='Cylindrée (CC)')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='voitures/')),
                ('etat', models.CharField(choices=[('Disponible', 'Disponible'), ('Réservée', 'Réservée'), ('Vendue', 'Vendue')], default='Disponible', max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voitures', to='voitures.marque')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voitures', to='voitures.modele')),
            ],
            options={
                'verbose_name': 'Voiture',
                'verbose_name_plural': 'Voitures',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('voiture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='voitures.voiture')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
            },
        ),
    ]
